summary: XML-based font configuration tools
webpage: https://wiki.freedesktop.org/www/Software/fontconfig
version: 2.15.0
bin-url: https://github.com/leleliu008/uppm-package-repository-android-26-aarch64/releases/download/2025.01.25/fontconfig-2.15.0-android-26-arm64-v8a.release.tar.xz
bin-sha: 6cde19738e6c55c7a3a8d690d0200ea3b9f10bd01441224f59caa333f49749d1
