summary: Manage compile and link flags for libraries
webpage: https://freedesktop.org/wiki/Software/pkg-config
version: 0.29.2
bin-url: https://github.com/leleliu008/uppm-package-repository-android-26-aarch64/releases/download/2025.01.25/pkg-config-0.29.2-android-26-arm64-v8a.release.tar.xz
bin-sha: 5c39022420e7f0b813ab384ec3b7d4bf154e2d8156be31e5114530a9e7d098c7
